name: Update DNS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Run script
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/Internet-Helper/GeoHideDNS/main/script.sh)
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DNS: ${{ vars.DNS }}
          REDIRECT: ${{ vars.REDIRECT }}
